### ISSUE TITLE
Waiting translations

### ISSUE THREAD

**Issue by ghost** [SeaDve/Delineate#11]
I see there are 5 finished translations and one %89 complated translation.

Unfontunatly there is no PR or action to merge them.

Thanks.

![resim](https://github.com/SeaDve/Delineate/assets/161761531/f6e0431b-98c8-4ec1-8e91-844cec819de1)

**Comment by PHHENS** [comment]
Can do french translation, how to proceed ?

**Comment by ghost** [comment]
> Can do french translation, how to proceed ?

It can be done on Weblate: https://hosted.weblate.org/engage/seadve/

**Comment by SeaDve** [comment]
This should now be fixed, thanks!
