### ISSUE TITLE
Is it on Flathub?

### ISSUE THREAD

**Issue by RasheedAZ** [SeaDve/Delineate#3]
Hi. Thanks for making this beautiful app. I could not find it on Flathub although it says: "Unlike Flatpak, take note that these packages are not officially supported by the developer."
https://github.com/SeaDve/dagger#-third-party-packages

**Comment by SeaDve** [comment]
Oh, that's misleading. It is not yet on Flathub, but will be soon. I'm just fixing leftover bugs and implementing the missing features.

**Comment by SeaDve** [comment]
Finally had the time to submit the app

https://github.com/flathub/flathub/pull/5617

**Comment by SeaDve** [comment]
Closing this as the app is already on Flathub.
